### ISSUE TITLE
How do I equip a Character based on the icon select?

### ISSUE THREAD

**Issue by JonBrant** [hippogamesunity/HeroEditorExtensionsHub#1]
I've got an equipment system working with the icon set, now I just need to know how to equip my character with the correct sprite that corresponds to the given icon. Thanks

**Comment by hippogamesunity** [comment]
Hi! You should create associated collection (similar to SpriteCollection)
and create links manually.

**Comment by JonBrant** [comment]
I just figured out how to load a piece of equipment based on its icon. I wasn't sure where to go from there, but an "interface" connection would be perfect. Thanks.

**Comment by hippogamesunity** [comment]
I'm working on it, but icon integration to Hero Editor is still in progress.

**Comment by hippogamesunity** [comment]
Thew new update is on review! Before you get it, backup your project!

**Comment by hippogamesunity** [comment]
@JonBrant Hi, Maybe you've missed something. But the asset was updated, it includes a part of Hero Editor now. The Example scene contains working examples of how character can equip items at runtime based on the icon selected.
![image](https://user-images.githubusercontent.com/7318172/92397644-d656ef80-f12f-11ea-9902-68ff5feb0b67.png)

Here is the link to the asset:
https://assetstore.unity.com/packages/2d/gui/icons/fantasy-inventory-icons-inventory-system-117467

Don't mix up it with the old Inventory asset that has nothing to do with Hero Editor:
https://assetstore.unity.com/packages/templates/systems/fantasy-inventory-system-102984

**Comment by JonBrant** [comment]
Yeah, I definitely missed this. Which hero editor is it in? Thanks. I'll
update my review later

**Comment by JonBrant** [comment]
Oh, looks like a separate asset, not included in any of the packs. Thought
I owned all your packs. I'm picking this up now.

Kinda hard to tell which packs are duplicates or included in others
sometimes. Sorry for the crappy review. Will check this out later
Thanks again

**Comment by JonBrant** [comment]
Ah. I do own it but I've never installed it for some reason. Wow. Lol. On
mobile at the moment, hard to check store.

Sorry for the spam. Have a good one

**Comment by hippogamesunity** [comment]
How did you navigate to HeroEditorExtensionsHub GitHub if you didn't use Inventory assets?
BTW Hero Editor wiki is https://github.com/hippogamesunity/HeroEditorHub/wiki/FAQ-&-Troubleshooting

**Comment by JonBrant** [comment]
I don't remember. Been a while
