### ISSUE TITLE
Inventory error

### ISSUE THREAD

**Issue by TorchwoodPL** [hippogamesunity/HeroEditorExtensionsHub#2]
I download clean inventory asset pack and when I try to lunch inventory scene I get:
http://img.h-y.eu/pic/161552332774.png

Even when I try to assing empty array to inventory variable I get more errors and even after dummy fixes ItemCoillection object still do not have option to load icon set.

**Comment by TorchwoodPL** [comment]
Also I have bought both:
https://assetstore.unity.com/packages/templates/systems/fantasy-inventory-system-102984 and
https://assetstore.unity.com/packages/2d/gui/icons/fantasy-inventory-icons-with-inventory-system-117467

It seams that boty packages have the same files, and in both I have errors but different ones, which package I use then?

**Comment by hippogamesunity** [comment]
Hi! Just tested Fantasy Inventory System and it works fine with Unity 2018.3.5 / Windows 10 / Visual Studio 2017.
Maybe you are trying to import both of these packages?)
Does it work with clean setup to an empty project?

**Comment by TorchwoodPL** [comment]
Yes I was trying to import both, to test and see which is cooler to use. On import https://assetstore.unity.com/packages/2d/gui/icons/fantasy-inventory-icons-with-inventory-system-117467  I have no errors.

Also Whe I have fantasy character pro editor and I iport Fanstasy monster on the same project there are some changes in PhotoMaker.cs and it gives some errors. Can you explain what packages can be used in the same porject? I have a few of yours :)

**Comment by hippogamesunity** [comment]
PhotoMaker is uncompleted feature, I will fix it soon. You can simply remove the script and PhotoMaker references.
You can combine all packages, but note that PRO version may contain more recent script updates, so I wouldn't recommend you to use Basic and PRO versions of different assets.

If you still have the issue with integrating Fantasy Heroes + Fantasy Monsters, please register it and I will check it!

**Comment by TorchwoodPL** [comment]
And tell me about inventory, which package have more recent one?

**Comment by hippogamesunity** [comment]
Fantasy Inventory Icons (with Inventory System) is more recient. If you are planning to use Icons Pack, leave this asset. Moreover, it will updated soon to cover new FH equipment.

**Comment by TorchwoodPL** [comment]
I just saw that when I try to ise Drag and Drop system, draggec icon became hure and cover all game screen, I tested it inside editor.

**Comment by TorchwoodPL** [comment]
Also Will you include more  non eq icons as well in future?

**Comment by hippogamesunity** [comment]
Yep, you can register your request here, on GitHub!

**Comment by hippogamesunity** [comment]
Thew new update is on review! Before you get it, backup your project!
