### ISSUE TITLE
GFX

### ISSUE THREAD

**Issue by TorchwoodPL** [hippogamesunity/HeroEditorExtensionsHub#3]
Do you have plan for, for example add back and front view for the characters or isometric stuff?

**Comment by hippogamesunity** [comment]
Yep)
![image](https://user-images.githubusercontent.com/7318172/54740924-d24ab100-4bcd-11e9-9ec8-9ba0571e028b.png)

**Comment by TorchwoodPL** [comment]
And when it will be available?

**Comment by hippogamesunity** [comment]
We've just started working on it, so not very soon.

**Comment by TorchwoodPL** [comment]
We are talking about weeks, months or years? Is that will be new pakage or update to one of already exist?

**Comment by hippogamesunity** [comment]
I suppose it can take a few months. And it will be completely different
asset without FH compatibility.
