### ISSUE TITLE
Missing icons list from Fantasy Inventory Icons

### ISSUE THREAD

**Issue by Williamxu98** [hippogamesunity/HeroEditorExtensionsHub#4]
Here's the list of missing icons that I discovered from Fantasy Inventory Icons.

Note that currently I've only used helmets, armors, weapons, and shields so there may be supplies or other types of items I missed. Those are important too! But I don't have the data on those yet. New items (ImperialTemplarHelm, DrifterKnightArmor, etc.) that are in the icon pack but not yet in Fantasy Heroes/Abandoned Workshop I also can't address since I don't have the data on those either.

Another note, I realize that Fantasy Undead icons haven't been included yet but I added them to this list anyways.

Helmets

RobberCap AbandonedWorkshop
ShamanMask4 [FullHair] SpellMasters/SwampLords
OldLeatherHelm Skeletons
OldPirateHat Skeletons
RedBandana [FullHair] Skeletons
SkeletonBrains Skeletons
SkeletonKing [FullHair] Skeletons
MummyHat1-4 Mummies
OldGladiatorHelm Skeletons
OldHornHelm Skeletons
OldCap Zombies

Armors

LegendaryMageArmor2 AbandonedWorkshop
RareMageArmor2 AbandonedWorkshop
CommonMageArmor2 AbandonedWorkshop
EpicMageArmor2 AbandonedWorkshop
SkeletonArmor2-6 Skeletons
ZombieClothes1-5 Zombies
MummyClothes1-4 Mummies
SkeletonKing Skeletons

MeleeWeapons1H

MagicSword [Paint] has another sword layered underneath
SkeletonHandLHook Undead
SkeletonHandRKnife Undead
SmallShowel Undead
BrokenSword Undead
EgyptianSword Undead
MummyWand Undead
StoneAxe Undead
OldPirateSaber Undead
BoneClub Undead
OldThrowingAxe Undead
OldWarriorSword Undead
WoodenClub Undead
SkeletonKingAxe Undead
OldWoodcutterAxe Undead
PharaohStaff Undead
RustedSword Undead
SkeletonSword Undead
WoodenStake Undead

MeleeWeapons2H

BloodAxe Undead
OldBattleAxe Undead
CursedSword Undead
HeavyAxe Undead
RustyPaleSword Undead
SkeletonKingAxe Undead
SkeletonKingAxeImproved Undead

Bows

SkeletonBow Undead
SkeletonBow2 Undead
SpineBow Undead
BladeBow Undead
EgyptianBow Undead

Shields

SkeletonLeftArmHook Undead
SkeletonShield1-3 Undead

**Comment by hippogamesunity** [comment]
Hi! I will check it soon, thanks!

**Comment by hippogamesunity** [comment]
Hi! I suppose some equipment may be removed/renamed. I can't find RobberCap or LegendaryMageArmor2 in Megapack. I will update extension assets soon, as only editor assets were updated a few days ago.

**Comment by Williamxu98** [comment]
Hi,

I actually ended up finding the icon for RobberCap in your icons pack:
![image](https://user-images.githubusercontent.com/15099346/55577668-17003d00-56e2-11e9-8a50-cb9b7c9d9c64.png)
![image](https://user-images.githubusercontent.com/15099346/55577704-2d0dfd80-56e2-11e9-9f6f-3dbbdc4703fe.png)

But the reason why my code was unable to get it from the list was because the 'C' in "RobberCap" for the name on file is actually a special unicode character:
![image](https://user-images.githubusercontent.com/15099346/55577779-5890e800-56e2-11e9-8521-87daf40fd950.png)
![image](https://user-images.githubusercontent.com/15099346/55577793-6181b980-56e2-11e9-9a29-f15e3026c03e.png)

Which explains why searching for it with regularly typed "RobberCap" didn't work.

Also, this is what I have for LegendaryMageArmor2 in my own records:
![image](https://user-images.githubusercontent.com/15099346/55577895-a60d5500-56e2-11e9-9d83-9c6c10963a2e.png)

**Comment by Williamxu98** [comment]
Also just noticed that you added an upgrade path for megapack, so I just bought it :)

**Comment by hippogamesunity** [comment]
Oh, it may be Russian letter 'С' =) Will check it)
