### ISSUE TITLE
How do i make this work for 4 characters? with different items?

### ISSUE THREAD

**Issue by FlufferbatIndustries** [hippogamesunity/HeroEditorExtensionsHub#6]
/// <summary>
		/// Initialize owned items (just for example).
		/// </summary>
		public void Initialize()
        {
			var inventory = ItemCollection.GeneratedItems.Select(i => new Item(i.Id, 1)).ToList(); // inventory.Clear();
			var equipped = new List<Item>
			{
				new Item("HawkHelm (Type=Helmet, Collection=Basic)"),
				new Item("BanditLightArmor [Paint] (Type=Armor, Collection=Basic)"),
				new Item("BanditLightArmor [Paint] (Type=Gloves, Collection=Basic)"),
				new Item("BanditLightArmor [Paint] (Type=Boots, Collection=Basic)"),
				new Item("ShortIronKatana [Paint] (Type=Weapon, Collection=Basic, Tags=Sword&1H)")
			};

            Bag.Initialize(ref inventory);
            Equipment.Initialize(ref equipped);
		}

**Comment by Flufferbat** [comment]
i tried to copy and rename file but it broke my game..

**Comment by Flufferbat** [comment]
also each time i seem to build the inventory system some icons are enabled and some aren't, as in different ones each time, and even if their marked "gold" they don't equip.. i had it working properly once and i think that's all.. I like the other guy managed to get stuff to equip on a playable dude but yea, it took all my items n i found this bit of code i obviously need to change, but yea i need to do it 4 times and well it wont let me copy/move/rename the file so like yea how can i do it in the one file? hoping its just one line of code per char or something lol..

**Comment by hippogamesunity** [comment]
You can't just copy and rename the script. You should implement your own logic that will fit your game design. Refer to ScrollInventory.cs line 73 to manage what prefabs are instantiated.

If you will have more specific questions, please ask them in separate threads.

**Comment by Flufferbat** [comment]
Soo.. are you saying i need to write a new collection file with that stuff in it and reference it in the "" in this bit? 		            var instance = Instantiate(item.Params.CollectionName == "" ? ItemNoSpritesPrefab : ItemPrefab, Grid.transform);
					var button = instance.GetComponent<InventoryItem>();
yikes lol..

**Comment by hippogamesunity** [comment]
No, you shouldn't create new ItemCollection. It's just item database, you can create lists from it (use LINQ,- Seletc, ToList) with different items based on what items your characters own. For example this will create a full list with all items available:
var inventory = ItemCollection.GeneratedItems.Select(i => new Item(i.Id, 1)).ToList();

**Comment by hippogamesunity** [comment]
More over you shouldn't use GeneratedItems. Instead, register your own items in ItemCollection.

**Comment by Flufferbat** [comment]
yea im only using the gen items to test it, i watched your video i get that lol, also see why you said that lag city lol.. I'm new to this so yea im trying to get what your saying.. but that totally is over my head rite now lol.. really don't want to bother you with my noobness, so i'l try to figure out what you just said..

Wait so i need to create a dropdown thing where the generated items list is? for each char differently? is that what you mean? lol

**Comment by hippogamesunity** [comment]
Yes, each character should have separate list of Item(s) (id + count). Based on this you should filter items from ItemCollection (using LINQ - Where, Select, ToList) to a new list and then display it.

**Comment by Flufferbat** [comment]
um yea i think you might misunderstand me, I want the stuff to be equipped not in the backpack, so my characters start the way i made them on start without having to equip it.. 

i want to controll this bit "new Item("HawkHelm (Type=Helmet, Collection=Basic)"),
			new Item("BanditLightArmor [Paint] (Type=Armor, Collection=Basic)"),
			new Item("BanditLightArmor [Paint] (Type=Gloves, Collection=Basic)"),
			new Item("BanditLightArmor [Paint] (Type=Boots, Collection=Basic)"),
			new Item("ShortIronKatana [Paint] (Type=Weapon, Collection=Basic, Tags=Sword&1H)")
		};"

**Comment by hippogamesunity** [comment]
There a 3 ways:
- place items to character backpack and update dummy using Inventory System
- set equipment directly (https://github.com/hippogamesunity/HeroEditorHub/wiki/Changing-equipment-at-runtime), Inventory System do the same things
- use json serialization to restore a character

**Comment by Flufferbat** [comment]
basically what i want is a drop point for each equip slot so i can drag n drop icons etc to change that part of the code, what line like this "public List<ItemParams> GeneratedItems;" can i use to get that to display?

**Comment by Flufferbat** [comment]
Refer to ExampleScripts/ChangingEquipment.cs: that script doesn't exist
![mmm](https://user-images.githubusercontent.com/25977219/56205483-3ce7f300-608d-11e9-97a9-f81b9a098cec.PNG)

**Comment by hippogamesunity** [comment]
Renamed to RuntimeSetup.cs, thanks!

вт, 16 апр. 2019 г. в 14:19, Flufferbat <notifications@github.com>:

**Comment by Flufferbat** [comment]
right lol np..

**Comment by FlufferbatIndustries** [comment]
Hmm ok I just did some stuff with grid snap instantiate objects so I think I know what you mean now..

**Comment by hippogamesunity** [comment]
=)
